name: kainuwa_academy
description: Kainuwa Digital Africa LMS Mobile App
publish_to: 'none'
version: 3.0.2+15

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  video_player: ^2.7.2
  chewie: ^1.7.4
  dio: ^5.4.0
  path_provider: ^2.1.2
  wakelock_plus: ^1.2.8
  webview_flutter: ^4.4.2
  cached_network_image: ^3.4.1
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  share_plus: ^7.2.2
  font_awesome_flutter: ^11.0.0
  flutter_markdown: ^0.7.3
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/kainuwa_logo.png
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 900